"""Step 3 — the knowledge graph store.

``InMemoryGraphStore`` is a small property graph: typed nodes, typed edges,
and — crucially for explainability — every edge keeps the evidence quote and
the chunk ids it was extracted from. ``to_cypher()`` exports the whole graph
as Cypher so the identical data can be loaded into Neo4j for the production
track (``Neo4jGraphStore``).
"""

from __future__ import annotations

import re

from .extract import Entity, Triple

TripleKey = tuple[str, str, str]  # (subject_id, predicate, object_id)


class InMemoryGraphStore:
    def __init__(self):
        self.entities: dict[str, Entity] = {}
        self._triples: dict[TripleKey, Triple] = {}
        self.provenance: dict[TripleKey, list[str]] = {}
        self._adjacency: dict[str, set[TripleKey]] = {}

    # -- construction -----------------------------------------------------

    def add_entity(self, entity: Entity) -> None:
        existing = self.entities.get(entity.entity_id)
        if existing is None:
            self.entities[entity.entity_id] = entity
        elif set(entity.aliases) - set(existing.aliases):
            merged = tuple(dict.fromkeys(existing.aliases + entity.aliases))
            self.entities[entity.entity_id] = Entity(
                entity_id=existing.entity_id,
                name=existing.name,
                entity_type=existing.entity_type,
                aliases=merged,
            )

    def add_triple(self, triple: Triple) -> None:
        key: TripleKey = (triple.subject, triple.predicate, triple.obj)
        if key not in self._triples:
            self._triples[key] = triple
            self.provenance[key] = []
            self._adjacency.setdefault(triple.subject, set()).add(key)
            self._adjacency.setdefault(triple.obj, set()).add(key)
        # The same fact stated in two documents becomes ONE edge with two
        # provenance entries — corroboration, not duplication.
        if triple.provenance not in self.provenance[key]:
            self.provenance[key].append(triple.provenance)

    # -- querying ----------------------------------------------------------

    def triples(self) -> list[Triple]:
        return list(self._triples.values())

    def find_entities(self, text: str) -> list[Entity]:
        """Entity linking: match entity names/aliases in free text on word
        boundaries. This is how a user's question gets anchored to nodes."""
        found = []
        for entity in self.entities.values():
            for candidate in (entity.name, *entity.aliases):
                if re.search(rf"\b{re.escape(candidate)}\b", text, re.IGNORECASE):
                    found.append(entity)
                    break
        return found

    def neighborhood(self, seed_ids: list[str], hops: int = 2) -> list[Triple]:
        """Collect every edge reachable within ``hops`` expansions of the
        seeds — the subgraph that multi-hop answers live in."""
        frontier = set(seed_ids)
        visited = set(seed_ids)
        collected: dict[TripleKey, Triple] = {}
        for _ in range(hops):
            next_frontier: set[str] = set()
            for entity_id in frontier:
                for key in self._adjacency.get(entity_id, ()):
                    collected.setdefault(key, self._triples[key])
                    for endpoint in (key[0], key[2]):
                        if endpoint not in visited:
                            visited.add(endpoint)
                            next_frontier.add(endpoint)
            frontier = next_frontier
            if not frontier:
                break
        return list(collected.values())

    def stats(self) -> dict:
        return {
            "entities": len(self.entities),
            "relationships": len(self._triples),
            "entity_types": sorted({e.entity_type for e in self.entities.values()}),
            "predicates": sorted({k[1] for k in self._triples}),
        }

    # -- export ------------------------------------------------------------

    def to_cypher(self) -> str:
        """Emit the graph as idempotent Cypher MERGE statements."""

        def q(value: str) -> str:
            return value.replace("\\", "\\\\").replace("'", "\\'")

        lines = ["// Generated by graphrag.graph_store — load with: cypher-shell < graph.cypher"]
        for e in self.entities.values():
            lines.append(
                f"MERGE (n:{e.entity_type} {{id: '{q(e.entity_id)}'}}) "
                f"SET n.name = '{q(e.name)}';"
            )
        for key, t in self._triples.items():
            sources = ", ".join(f"'{q(p)}'" for p in self.provenance[key])
            lines.append(
                f"MATCH (a {{id: '{q(t.subject)}'}}), (b {{id: '{q(t.obj)}'}}) "
                f"MERGE (a)-[r:{t.predicate}]->(b) "
                f"SET r.evidence = '{q(t.evidence)}', r.sources = [{sources}];"
            )
        return "\n".join(lines)


class Neo4jGraphStore:
    """Production adapter: mirror the in-memory graph into Neo4j.

    Usage (after ``docker compose up -d`` in the course root)::

        store = Neo4jGraphStore("bolt://localhost:7687", "neo4j", "graphrag-course")
        store.load(memory_store)
    """

    def __init__(self, uri: str, user: str, password: str):
        try:
            from neo4j import GraphDatabase
        except ImportError as exc:  # pragma: no cover - live track only
            raise RuntimeError(
                "The Neo4j track needs the driver: pip install neo4j"
            ) from exc
        self._driver = GraphDatabase.driver(uri, auth=(user, password))

    def load(self, store: InMemoryGraphStore) -> None:
        with self._driver.session() as session:
            for statement in store.to_cypher().split(";\n"):
                statement = statement.strip().rstrip(";")
                if statement and not statement.startswith("//"):
                    session.run(statement)

    def close(self) -> None:
        self._driver.close()
